### ISSUE TITLE
Project.toml does not match 

### ISSUE THREAD

**Issue by musm** [julia-actions/RegisterAction#5]
This used to work; however I'm running into a mysterious error all of the sudden, when attempting to create a patch release on a  non-master branch. 
```
RequestError [HttpError]: Project.toml does not match 73f8c79201f1bbb6d7e87e64a15d6bcd9db2d1a0

```
Log: https://github.com/JuliaIO/HDF5.jl/runs/3165622889?check_suite_focus=true

**Comment by christopher-dG** [comment]
Hi, sorry to have missed this! I think I see the bug, it's computing that hash from the Project.toml in the main branch, not on the release branch. I'll hopefully get a fix out this evening!
